### ISSUE TITLE
Partícula - Skill Healer

### ISSUE THREAD

**Issue by leodimano** [GroupByStudios/TDS_Gauss#11]

**Comment by LucasGarcia12** [comment]
**Abell** - Munição no Chão
**Emma** - Cura especifico (Self ou Outros) ‐ Kit de Cura no Chão 
**Otto** - Mira por 2 segundos para dar dano crítico e 5X Dano Critico, se for atingido cancela o ataque e atravessa
**Ollie** - Taunt em Área ‐ Provoca os inimigos para focar o ataque
**Calvin** - Frenesi ‐ Temporariamente Atira mais rápido e Mais Dano

**Comment by LucasGarcia12** [comment]
Implementado no projeto
